# Generated by Django 5.2.8 on 2026-01-02 09:48

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_work_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Default Work Start')),
                ('default_work_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Default Work End')),
                ('default_break_duration', models.PositiveIntegerField(default=60, verbose_name='Default Break Duration (minutes)')),
                ('min_advance_booking', models.PositiveIntegerField(default=1, help_text='Minimum hours before appointment can be booked', verbose_name='Minimum Advance Booking (hours)')),
                ('max_daily_hours', models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Maximum Daily Hours')),
                ('overtime_threshold', models.PositiveIntegerField(default=40, verbose_name='Overtime Threshold (hours/week)')),
                ('show_staff_photos', models.BooleanField(default=True, verbose_name='Show Staff Photos')),
                ('show_staff_bio', models.BooleanField(default=True, verbose_name='Show Staff Bio')),
                ('allow_staff_selection', models.BooleanField(default=True, help_text='Allow customers to select specific staff member', verbose_name='Allow Staff Selection')),
                ('notify_new_appointment', models.BooleanField(default=True, verbose_name='Notify on New Appointment')),
                ('notify_cancellation', models.BooleanField(default=True, verbose_name='Notify on Cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Configuration',
                'verbose_name_plural': 'Staff Configuration',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Photo')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Employee ID')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='Status')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('specialties', models.TextField(blank=True, help_text='Comma-separated list of specialties', verbose_name='Specialties')),
                ('is_bookable', models.BooleanField(default=True, help_text='Can be booked for appointments', verbose_name='Is Bookable')),
                ('color', models.CharField(blank=True, help_text='Color for calendar display', max_length=7, verbose_name='Calendar Color')),
                ('booking_buffer', models.PositiveIntegerField(default=0, help_text='Buffer time between appointments', verbose_name='Booking Buffer (minutes)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Hourly Rate')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission Rate (%)')),
                ('user_id', models.PositiveIntegerField(blank=True, help_text='Link to LocalUser for login access', null=True, verbose_name='User ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='staff.staffrole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['order', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Schedule', max_length=100, verbose_name='Schedule Name')),
                ('is_default', models.BooleanField(default=True, verbose_name='Is Default')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Effective From')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Effective Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staffmember', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Staff Schedule',
                'verbose_name_plural': 'Staff Schedules',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('training', 'Training'), ('other', 'Other')], default='vacation', max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(blank=True, help_text='For partial day off', null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, help_text='For partial day off', null=True, verbose_name='End Time')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Full Day')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='approved', max_length=20, verbose_name='Status')),
                ('approved_by_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approved By')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='staff.staffmember', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Time Off',
                'verbose_name_plural': 'Time Off',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField(help_text='ID from services module', verbose_name='Service ID')),
                ('service_name', models.CharField(help_text='Cached service name', max_length=200, verbose_name='Service Name')),
                ('custom_duration', models.PositiveIntegerField(blank=True, help_text='Override service default duration', null=True, verbose_name='Custom Duration (minutes)')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override service default price', max_digits=10, null=True, verbose_name='Custom Price')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/specialty service for this staff', verbose_name='Primary Service')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staffmember', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Staff Service',
                'verbose_name_plural': 'Staff Services',
                'ordering': ['-is_primary', 'service_name'],
                'unique_together': {('staff', 'service_id')},
            },
        ),
        migrations.CreateModel(
            name='StaffWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Break Start')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Break End')),
                ('is_working', models.BooleanField(default=True, verbose_name='Is Working Day')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='staff.staffschedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
    ]
